/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.mibcxb.tool.app;

import com.mibcxb.tool.app.ui.main.MainView;

import javax.swing.*;

public class McToolApp {
    public static void main(String[] args) {
        JFrame frame = new JFrame("McTool");
        frame.setSize(640, 480);
        frame.setContentPane(new MainView().create());
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setVisible(true);
    }
}
